/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BlockchainVoting } from "./BlockchainVoting";
export * as factories from "./factories";
export { BlockchainVoting__factory } from "./factories/BlockchainVoting__factory";
