name: Deploy Smart Contract

on:
    push:
        branches:
            - main # Trigger on pushes to the 'main' branch

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            # Step 1: Checkout the repository
            - name: Checkout code
              uses: actions/checkout@v3

            # Step 2: Set up Node.js environment
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18 # Use Node.js 18

            - name: navigate to voting
              run: ls -la

            # Step 3: Install dependencies
            - name: Install dependencies
              run: npm install

            # Step 4: Compile the smart contracts
            - name: Compile Contracts
              run: npx hardhat compile

            # Step 5: Deploy to Sepolia Testnet
            - name: Deploy Contracts
              env:
                  ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
                  WALLET_PRIVATE_KEY: ${{ secrets.WALLET_PRIVATE_KEY }}
              run: npx hardhat run scripts/deploy.js --network sepolia

            # Step 6: Verify on Etherscan (Optional)
            - name: Verify Contract on Etherscan
              if: success()
              env:
                  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
              run: |
                  npx hardhat verify --network sepolia $(cat contract-address.txt)
