name: Deploy Smart Contract

on:
    push:
        branches:
            - main # Trigger on pushes to the 'main' branch

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Navigate to project folder
              working-directory: ./blockchain-voting
              run: pwd

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install dependencies
              working-directory: ./blockchain-voting
              run: npm install

            - name: Compile Contracts
              working-directory: ./blockchain-voting
              env:
                  ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
                  WALLET_PRIVATE_KEY: ${{ secrets.WALLET_PRIVATE_KEY }}
                  DEPLOYED_CONTRACT_ADDRESS:
                      ${{ secrets.DEPLOYED_CONTRACT_ADDRESS }}
              run: npx hardhat compile

            - name: Deploy Contracts
              working-directory: ./blockchain-voting
              env:
                  ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
                  WALLET_PRIVATE_KEY: ${{ secrets.WALLET_PRIVATE_KEY }}
                  DEPLOYED_CONTRACT_ADDRESS:
                      ${{ secrets.DEPLOYED_CONTRACT_ADDRESS }}
              run: npx hardhat run scripts/deploy.js --network sepolia
